# Generated by Django 4.1.13 on 2024-07-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='au8thor',
            new_name='author',
        ),
    ]
